"""Secure Cloud Architecture Cheat Sheet classifier built on the TypeSafe System One API.

Classifies input text against sub-categories drawn from the OWASP
"Secure Cloud Architecture Cheat Sheet" cheat sheet:
https://cheatsheetseries.owasp.org/cheatsheets/Secure_Cloud_Architecture_Cheat_Sheet.html

Each sub-category is scored independently as a TypeSafe Noul question (does
the input relate to / exhibit this issue?), so a single input can match zero,
one, or several categories at once. All categories are evaluated in one
parallel system_one() call.

Usage:
    python secure_cloud_architecture_classifier.py "some text to classify"
    python secure_cloud_architecture_classifier.py --file path/to/content.txt
    echo "some text" | python secure_cloud_architecture_classifier.py
"""

import argparse
import sys

from typesafe_sdk import Noul, TypeSafeClient

# --- Standard classifier module interface (used by run_all_classifiers.py) ---
CHEATSHEET_NAME = "Secure Cloud Architecture Cheat Sheet"
CHEATSHEET_URL = (
    "https://cheatsheetseries.owasp.org/cheatsheets/Secure_Cloud_Architecture_Cheat_Sheet.html"
)

# Sub-categories drawn from the cheat sheet's key sections / named risks /
# recommendations. Each description is written so Jev (the TypeSafe model)
# can distinguish it from neighboring categories -- be specific about what
# does and does not count.
CATEGORIES = {
    "public_object_storage_exposure": (
        "Sensitive or generic resources are stored in a publicly accessible "
        "object storage configuration (e.g. an open S3-style bucket), giving "
        "unauthenticated access and reconnaissance value to attackers."
    ),
    "overly_broad_iam_credential": (
        "Access to object storage or other cloud resources is mediated by a "
        "broad, hardcoded, or loosely-scoped IAM policy/credential whose loss "
        "would grant wide control-plane access."
    ),
    "insecure_signed_url_generation": (
        "Signed URLs for object storage are generated by custom or dynamic code "
        "susceptible to injection, lack an expiration, or grant anonymous access "
        "to anyone possessing the URL."
    ),
    "missing_network_segmentation": (
        "An application architecture lacks VPC/subnet segmentation separating "
        "components, so there is no boundary between internet-facing and internal "
        "systems."
    ),
    "sensitive_component_in_public_subnet": (
        "A database, backend server, or other sensitive component deemed 'too "
        "risky for direct internet access' is placed in a public subnet with "
        "direct internet routing instead of a private subnet."
    ),
    "excessive_trust_boundary_bypass": (
        "A component skips authentication/authorization re-verification when "
        "calling another component across a trust boundary (a 'high trust' anti- "
        "pattern), effectively handing untrusted input directly to a high- "
        "criticality resource."
    ),
    "missing_threat_modeling": (
        "An architecture decision is made without a preceding risk analysis, "
        "threat modeling exercise, or attack-surface assessment to scope what "
        "threats, likelihoods, and business impacts apply."
    ),
    "insecure_bastion_or_dev_access": (
        "A developer access point such as a bastion host is deployed in a public "
        "subnet without careful hardening, creating a potentially insecure entry "
        "point into otherwise private infrastructure."
    ),
}


def classify_with_nouls(text: str) -> dict:
    """Return dict of category -> probability (0-1), one Noul per category,
    all evaluated in a single parallel call."""
    with TypeSafeClient() as client:
        result = client.system_one(
            state=text,
            questions={
                name: Noul(instructions=f"Does the input relate to or exhibit this issue: {desc}")
                for name, desc in CATEGORIES.items()
            },
        )
    return {name: answer.noul for name, answer in result.nouls.items()}


def print_table(headers, rows) -> None:
    """Print `rows` (each a tuple of column values) as a simple aligned table."""
    widths = [
        max(len(str(cell)) for cell in (header, *(row[i] for row in rows)))
        for i, header in enumerate(headers)
    ]
    def fmt(row):
        return "  ".join(str(cell).ljust(width) for cell, width in zip(row, widths))

    print(fmt(headers))
    print("  ".join("-" * width for width in widths))
    for row in rows:
        print(fmt(row))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("text", nargs="?", help="Text to classify")
    parser.add_argument("--file", help="Read text to classify from a file")
    args = parser.parse_args()

    if args.file:
        with open(args.file, "r", encoding="utf-8") as fh:
            text = fh.read()
    elif args.text:
        text = args.text
    else:
        text = sys.stdin.read()

    if not text.strip():
        parser.error("no input text provided")

    scores = classify_with_nouls(text)
    rows = [
        (name, f"{prob:.3f}")
        for name, prob in sorted(scores.items(), key=lambda kv: -kv[1])
    ]
    print_table(("category", "probability"), rows)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
